# Generated by Django 3.2.9 on 2021-11-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20211121_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='art',
            field=models.ImageField(blank=True, upload_to='post_list'),
        ),
    ]
