# Generated by Django 3.2.9 on 2021-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
